### ISSUE TITLE
приведення типів

### ISSUE THREAD

**Issue by pecourses** [ArtyomHloba/JS_DZ#1]
https://github.com/ArtyomHloba/JS_DZ/blob/c2873107ed183bf332a2baf3c9d70b5cfdb04da1/assets/js/index.js#L53
- щоб напевно уникнути неявного перетворення типів і потенційних пов'язаних з ним проблем рекомендується прописувати явне перетворення, як тут:
https://github.com/ArtyomHloba/JS_DZ/blob/c2873107ed183bf332a2baf3c9d70b5cfdb04da1/assets/js/index.js#L57

**Comment by ArtyomHloba** [comment]
Спасибо, дописал.
