### ISSUE TITLE
ширина і адаптивність

### ISSUE THREAD

**Issue by pecourses** [ArtyomHloba/JS_DZ#12]
https://github.com/ArtyomHloba/JS_DZ/blob/56d600271b621845859691effd0e0ed97e33207e/assets/css/style.css#L121
- тут вилазе невеличкий баг, пов'язаний з дефолтною поведінкою інпутів/селектів/textarea:
![image](https://github.com/ArtyomHloba/JS_DZ/assets/67504221/e59687c0-02f6-480d-81c3-6147863e245c)
Щоб позбутися, можна прописати для `.form-input` `width: 100%;`

**Comment by ArtyomHloba** [comment]
Фиксанул, в некст коммите исправлено
