### ISSUE TITLE
присвоєння vs порівняння

### ISSUE THREAD

**Issue by pecourses** [ArtyomHloba/JS_DZ#2]
https://github.com/ArtyomHloba/JS_DZ/blob/b1946824a31bf955203e62b7ef2e171da5a60b57/assets/js/index.js#L14
- такий код не дуже читається і може збивати з пантелику. Краще розділяти присвоювання і використання:
```javascript
const isOnline = false; 

isOnline ? console.log(`Онлайн`) : console.log(`Ваше повідомлення буде відправлено при під'єднанні до мережі Інтернет`); 
```

**Comment by ArtyomHloba** [comment]
Я так сначала и сделал, но потом думал, почему бы не оптимизировать в строчку все хах. в некст коммите все фиксану
